let token=localStorage.monitorToken||'',boot=null,deviceId=localStorage.deviceId||crypto.randomUUID(),scanner=null,scanContext=null,mode='ENTRADA',syncedCount=0,scanBusy=false;
function beep(ok=true){try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=ok?880:330;g.gain.value=.08;o.connect(g);g.connect(ctx.destination);o.start();setTimeout(()=>{o.stop();ctx.close()},120)}catch(_){}}
function bool(v){return v===true||['true','sim','s','1','yes'].includes(String(v??'').trim().toLowerCase())}
function fmtMin(v){const n=Math.max(0,Number(v)||0),h=Math.floor(n/60),m=Math.floor(n%60);return h?`${h}h ${String(m).padStart(2,'0')}min`:`${m} min`}
function norm(v){return String(v??'').trim().toLowerCase()}
function participantFromCode(code){const q=norm(code),digits=q.replace(/\D/g,'');return (boot?.participants||[]).find(p=>[p.NUMERO_INSCRICAO,p.numero_inscricao,p.QR_TOKEN,p.qr,p.PARTICIPANT_ID,p.id].some(v=>norm(v)===q||((digits.length>=6)&&String(v??'').replace(/\D/g,'')===digits)))||null}

function activityById(id){return (boot?.activities||[]).find(a=>a.ACTIVITY_ID===id)}
function activityTimes(a){if(!a)return null;const d=String(a.DATA||'').split('T')[0],i=String(a.HORARIO_INICIO||'').trim(),f=String(a.HORARIO_FIM||'').trim();if(!d||!i||!f)return null;const start=new Date(`${d}T${i.length===5?i+':00':i}`).getTime(),end=new Date(`${d}T${f.length===5?f+':00':f}`).getTime();return Number.isFinite(start)&&Number.isFinite(end)?{start,end}:null}
function activitiesOverlap(a,b){const x=activityTimes(a),y=activityTimes(b);return !!(x&&y&&x.start<y.end&&y.start<x.end)}
function isRegistered(pid,aid){return (boot?.registrations||[]).some(r=>(r.PARTICIPANT_ID||r.participant_id)===pid&&(r.ACTIVITY_ID||r.activity_id)===aid&&String(r.STATUS||r.status||'ATIVO').toUpperCase()!=='CANCELADA')}
function isFull(a){const cap=Number(a?.CAPACIDADE||0),used=Number(a?.INSCRITOS||0);return cap>0&&used>=cap}
function cachedInsideElsewhere(pid,aid){const target=activityById(aid);return (boot?.attendance_states||[]).map(st=>({st,a:activityById(st.activity_id||st.ACTIVITY_ID)})).find(x=>(x.st.participant_id||x.st.SUBJECT_ID)===pid&&x.a&&x.a.ACTIVITY_ID!==aid&&activitiesOverlap(x.a,target))||null}
async function localParticipantState(pid,aid){const q=await DB.allQueue(),scans=q.filter(x=>x.kind==='scan'&&x.payload.subject_type==='PARTICIPANT'&&x.payload.participant_id===pid);const queuedHere=scans.filter(x=>x.payload.activity_id===aid).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))).at(-1);const serverInside=(boot?.attendance_states||[]).some(st=>(st.participant_id||st.SUBJECT_ID)===pid&&(st.activity_id||st.ACTIVITY_ID)===aid&&String(st.estado||st.ESTADO).toUpperCase()==='DENTRO');const here=queuedHere|| (serverInside?{payload:{tipo:'ENTRADA',activity_id:aid,participant_id:pid},created_at:'SERVER'}:null);const other=scans.filter(x=>x.payload.activity_id!==aid&&x.payload.tipo==='ENTRADA').sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))).at(-1);return {here,other}}

localStorage.deviceId=deviceId;window.token=token;const $=id=>document.getElementById(id);
function busy(v){$('busy').classList.toggle('hidden',!v)}function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}function feedback(kind,title,name,text){$('feedback').className='feedback '+(kind||'');$('fbTitle').textContent=title;$('fbName').textContent=name||'';$('fbText').textContent=text||'';$('feedback').classList.remove('hidden');navigator.vibrate?.(kind==='bad'?[100,60,100]:80);setTimeout(()=>$('feedback').classList.add('hidden'),1100)}
async function updateCounts(){const q=await DB.allQueue();$('pending').textContent=q.length;$('synced').textContent=syncedCount}
function uuid(){return crypto.randomUUID()}function now(){return new Date().toISOString()}
async function init(){await DB.open();$('api').value=API.url;setTimeout(()=>$('splash').classList.add('hidden'),650);if(token){try{await loadBootstrap();$('app').classList.remove('hidden')}catch(e){token='';localStorage.removeItem('monitorToken');$('login').classList.remove('hidden')}}else $('login').classList.remove('hidden');updateNet();updateCounts();setInterval(()=>SYNC.run().catch(()=>{}),15000)}
$('loginBtn').onclick=async()=>{try{busy(true);API.setUrl($('api').value);const r=await API.post({action:'login',email:$('email').value,password:$('password').value,device:{device_id:deviceId,nome:navigator.userAgent.slice(0,80),plataforma:'PWA',versao_app:'2.1.0'}});if(!r.success)throw new Error(r.error);token=r.token;window.token=token;localStorage.monitorToken=token;if(r.force_password_change){const nova=prompt('Primeiro acesso: crie uma nova senha com pelo menos 8 caracteres.');if(!nova)throw new Error('Troca de senha obrigatória');const c=await API.post({action:'change_password',token,nova_senha:nova});if(!c.success)throw new Error(c.error)}await loadBootstrap();$('login').classList.add('hidden');$('app').classList.remove('hidden')}catch(e){$('loginMsg').textContent=e.message}finally{busy(false)}};
$('logout').onclick=()=>{localStorage.removeItem('monitorToken');location.reload()};
async function loadBootstrap(){busy(true);try{const r=await API.post({action:'bootstrap',token,evento_id:'FPBF26'});if(!r.success)throw new Error(r.error);boot=r;await DB.set('bootstrap',r);renderHome()}catch(e){const local=await DB.get('bootstrap');if(!local)throw e;boot=local;renderHome();feedback('warn','MODO OFFLINE','','Usando a última base sincronizada')}finally{busy(false)}}
function renderHome(){const m=boot.monitor;$('who').textContent=`${m.nome} • ${m.nivel}`;$('hello').textContent='Olá, '+m.nome.split(' ')[0];$('registrationCard').classList.toggle('hidden',!m.permissions.inscrever);$('presentationCard').classList.toggle('hidden',!m.permissions.apresentar);$('monitorCard').classList.toggle('hidden',!m.permissions.freq_mon);const freqActs=boot.activities.filter(a=>bool(a.CONTROLA_FREQUENCIA));const opts='<option value="">Selecione...</option>'+freqActs.map(a=>`<option value="${a.ACTIVITY_ID}">${a.NOME}</option>`).join('');$('freqActivity').innerHTML=opts;const monOpts='<option value="">Selecione...</option>'+boot.activities.map(a=>`<option value="${a.ACTIVITY_ID}">${a.NOME}</option>`).join('');$('monActivity').innerHTML=monOpts;renderRegistrationActivities();renderWorks()}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));document.querySelectorAll('.back').forEach(b=>b.onclick=()=>show('home'));document.querySelectorAll('.mode button').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.parentElement.id!=='monMode')mode=b.dataset.mode});
document.querySelectorAll('[data-scan]').forEach(b=>b.onclick=()=>{const type=b.dataset.scan,aid=type==='monitor'?$('monActivity').value:$('freqActivity').value;if(!aid)return feedback('bad','SELECIONE A ATIVIDADE','','');const m=type==='monitor'?$('monMode').querySelector('.active').dataset.mode:mode;openScanner({kind:type,activity_id:aid,mode:m,title:boot.activities.find(a=>a.ACTIVITY_ID===aid)?.NOME})});
document.querySelectorAll('[data-manual]').forEach(b=>b.onclick=()=>{const aid=$('freqActivity').value;if(!aid)return feedback('bad','SELECIONE A ATIVIDADE','','');const q=prompt('Número de inscrição ou conteúdo do QR:');if(q)handleCode(q,{kind:'participant',activity_id:aid,mode,title:boot.activities.find(a=>a.ACTIVITY_ID===aid)?.NOME,origem:'MANUAL'})});
function renderRegistrationActivities(){$('registrationActivities').innerHTML=boot.activities.filter(a=>bool(a.PERMITE_INSCRICAO_MONITOR)).map(a=>{const cap=Number(a.CAPACIDADE||0),used=Number(a.INSCRITOS||0);return `<div class="activityItem"><h3>${a.NOME}</h3><p>${a.TIPO} • ${used}${cap?' / '+cap:''} inscritos ${cap?'• '+Math.max(0,cap-used)+' vagas':''}</p><button onclick="openScanner({kind:'registration',activity_id:'${a.ACTIVITY_ID}',title:'${String(a.NOME).replace(/'/g,"\\'")}'})">Inscrever participante</button></div>`}).join('')||'<p>Nenhuma atividade liberada.</p>'}
function renderWorks(){const q=($('workSearch').value||'').toLowerCase();$('workList').innerHTML=(boot.works||[]).filter(w=>(w.TITULO+' '+w.AUTORES).toLowerCase().includes(q)).map(w=>`<div class="activityItem"><h3>${w.TITULO}</h3><p>${w.AUTORES}<br><b>${w.MODALIDADE}</b></p><button onclick="openScanner({kind:'presentation',work_id:'${w.WORK_ID}',title:'${String(w.TITULO).replace(/'/g,"\\'")}'})">Registrar apresentação</button></div>`).join('')}$('workSearch').oninput=renderWorks;
async function openScanner(ctx){scanContext=ctx;scanBusy=false;$('scanMode').textContent=ctx.mode||ctx.kind.toUpperCase();$('scanTitle').textContent=ctx.title||'';show('scanner');if(scanner)try{await scanner.stop()}catch(_){};scanner=new Html5Qrcode('reader');try{await scanner.start({facingMode:'environment'},{fps:12,qrbox:{width:250,height:250}},code=>handleCode(code,ctx))}catch(e){feedback('bad','CÂMERA INDISPONÍVEL','',e.message)}}window.openScanner=openScanner;
async function stopScanner(){if(scanner){try{await scanner.stop()}catch(_){}scanner=null}}document.querySelector('.backScan').onclick=async()=>{await stopScanner();show('home')};$('manualGo').onclick=()=>{const q=$('manualQr').value.trim();if(q)handleCode(q,scanContext)};
async function handleCode(code,ctx){if(!ctx||scanBusy)return;scanBusy=true;await stopScanner();beep(true);try{if(ctx.kind==='participant'||ctx.kind==='monitor'){
 const participant=ctx.kind==='participant'?participantFromCode(code):null;
 if(ctx.kind==='participant'&&!participant){beep(false);feedback('bad','NÃO ENCONTRADO','','Participante não está no cache. Sincronize a base antes da atividade.');setTimeout(()=>openScanner(ctx),2000);return}
 const pid=participant&&(participant.PARTICIPANT_ID||participant.id||participant.NUMERO_INSCRICAO||participant.numero_inscricao);
 if(ctx.kind==='participant'){
   const st=await localParticipantState(pid,ctx.activity_id),last=st.here?.payload?.tipo,act=activityById(ctx.activity_id);
   if(ctx.mode==='ENTRADA'&&!isRegistered(pid,ctx.activity_id)&&isFull(act)){beep(false);feedback('warn','NÃO INSCRITO',participant.NOME||participant.nome||'','ATIVIDADE LOTADA');setTimeout(()=>openScanner(ctx),2000);return}
   let switchFrom=null;
   if(ctx.mode==='ENTRADA'){switchFrom=cachedInsideElsewhere(pid,ctx.activity_id);if(switchFrom){const trocar=confirm(`${participant.NOME||participant.nome||'Participante'} já está em "${switchFrom.a.NOME}" no mesmo horário.\n\nDeseja trocar para "${act?.NOME||'esta atividade'}"?`);if(!trocar){feedback('warn','TROCA CANCELADA',participant.NOME||participant.nome||'','Nenhum registro foi criado.');setTimeout(()=>openScanner(ctx),2000);return}}}
   if(ctx.mode==='ENTRADA'&&last==='ENTRADA'){beep(false);feedback('warn','ENTRADA JÁ REGISTRADA',participant.NOME||participant.nome||'', 'Nenhum novo registro foi criado.');setTimeout(()=>openScanner(ctx),2000);return}
   if(ctx.mode==='SAIDA'&&last!=='ENTRADA'){beep(false);feedback('warn','SEM ENTRADA',participant.NOME||participant.nome||'','Não há entrada local aberta nesta atividade.');setTimeout(()=>openScanner(ctx),2000);return}
 }
 const payload={scan_id:uuid(),evento_id:'FPBF26',qr_token:code,participant_id:pid||'',activity_id:ctx.activity_id,device_id:deviceId,captured_at:now(),tipo:ctx.mode,subject_type:ctx.kind==='monitor'?'MONITOR':'PARTICIPANT',origem:ctx.origem||'PWA',confirm_switch:!!switchFrom};
 await DB.enqueue({id:payload.scan_id,kind:'scan',payload,created_at:now()});
 feedback('warn',ctx.mode+' SALVA',participant?(participant.NOME||participant.nome||''):'','SALVO NO DISPOSITIVO • Pendente de sincronização');
 await updateCounts();setTimeout(()=>openScanner(ctx),2000);return}
if(ctx.kind==='registration'){const participant=participantFromCode(code);if(!participant){beep(false);feedback('bad','NÃO ENCONTRADO','','Sincronize a base para atualizar os participantes.');setTimeout(()=>openScanner(ctx),2000);return}const payload={registration_id:uuid(),activity_id:ctx.activity_id,participant_id:participant.PARTICIPANT_ID||participant.id||participant.NUMERO_INSCRICAO||participant.numero_inscricao,qr_token:code,device_id:deviceId,captured_at:now()};await DB.enqueue({id:payload.registration_id,kind:'registration',payload,created_at:now()});feedback('warn','INSCRIÇÃO SALVA',participant.NOME||participant.nome||'','Pendente de sincronização');await updateCounts();setTimeout(()=>openScanner(ctx),2000);return}
 if(ctx.kind==='presentation'){const payload={presentation_id:uuid(),work_id:ctx.work_id,qr_token:code,device_id:deviceId,captured_at:now(),origem:'PWA'};await DB.enqueue({id:payload.presentation_id,kind:'presentation',payload,created_at:now()});feedback('warn','APRESENTAÇÃO SALVA','','Pendente de sincronização');await updateCounts();setTimeout(()=>show('presentation'),2000);return}
 }catch(e){feedback('bad','ERRO','',e.message);setTimeout(()=>openScanner(ctx),1300)}finally{busy(false)}}
$('syncNow').onclick=async()=>{busy(true);try{await SYNC.run();await loadBootstrap();feedback('','SINCRONIZADO','','Pendências enviadas e cache atualizado')}catch(e){feedback('bad','FALHA NA SINCRONIZAÇÃO','',e.message)}finally{busy(false)}};
function updateNet(){$('net').textContent=navigator.onLine?'● ONLINE':'● OFFLINE';$('net').className=navigator.onLine?'online':'offline'}window.addEventListener('online',()=>{updateNet()});window.addEventListener('offline',updateNet);init();
