(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FPBFImport=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
  function decodeCsvBuffer(buffer){let text='',encoding='UTF-8';try{text=new TextDecoder('utf-8',{fatal:true}).decode(buffer);}catch(_){encoding='Windows-1252';text=new TextDecoder('windows-1252').decode(buffer);}return {text:text.replace(/^\uFEFF/,''),encoding};}
  function detectDelimiter(text){const lines=String(text).split(/\r?\n/).filter(x=>x.trim()).slice(0,8),candidates=[';',',','\t'];let best=';',score=-1;for(const d of candidates){const counts=lines.map(l=>countOutsideQuotes(l,d));const avg=counts.reduce((a,b)=>a+b,0)/(counts.length||1),stable=counts.filter(x=>x===counts[0]).length;const s=avg*10+stable;if(s>score){score=s;best=d;}}return best;}
  function countOutsideQuotes(line,d){let q=false,n=0;for(let i=0;i<line.length;i++){if(line[i]==='"'){if(q&&line[i+1]==='"')i++;else q=!q;}else if(!q&&line[i]===d)n++;}return n;}
  function parseDelimited(text,delimiter){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(ch===delimiter&&!q){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[];}else cell+=ch;}if(cell||row.length){row.push(cell);if(row.some(v=>String(v).trim()!==''))rows.push(row);}if(!rows.length)return[];const headers=rows[0].map(x=>String(x).trim());return rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}
  function mapEvenRows(raw){return (raw||[]).map((r,i)=>{const keys=Object.keys(r),get=(...names)=>{for(const k of keys)if(names.includes(norm(k)))return r[k];return ''};return {_linha:i+2,id_even:String(get('id','ideven')??'').trim(),nome:String(get('nome')??'').trim(),email:String(get('email')??'').trim(),data_inscricao:String(get('datainscricao')??'').trim(),numero_inscricao:String(get('numerodeinscricao','numeroinscricao','ninscricao')??'').trim().replace(/\.0$/,''),categoria:String(get('categoria')??'').trim()};});}
  return {norm,decodeCsvBuffer,detectDelimiter,parseDelimited,mapEvenRows};
});
