'use strict';
const C=window.III_FPBF_CONFIG, $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,stream:null,running:false,detector:null,lastDetect:0,deviceId:null};
const DBN='iii_fpbf_credenciamento', DBV=1;
function uid(){return (crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2))}
function deviceId(){let x=localStorage.getItem('iii_device');if(!x){x='WEB-'+uid().slice(0,12).toUpperCase();localStorage.setItem('iii_device',x)}return x}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DBN,DBV);r.onupgradeneeded=()=>{const d=r.result;['monitors','base','program','config','records'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:n==='records'?'id':'_key'})})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function put(store,obj){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).put(obj);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function all(store){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function replace(store,rows){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite'),s=t.objectStore(store);s.clear();rows.forEach((o,i)=>s.put({...o,_key:String(o._key??o['ID Monitor']??o['Nº Inscrição']??o['Código Atividade']??i)}));t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
function val(o,names){for(const n of names)if(o&&o[n]!==undefined&&o[n]!==null&&String(o[n]).trim()!=='')return String(o[n]).trim();return ''}
function extractQR(raw){raw=String(raw||'').trim();if(/^\d{8}$/.test(raw))return raw;const clean=raw.split('?')[0];const m=clean.match(/(\d{8})$/);return m?m[1]:''}
function msg(el,text,kind='info'){el.innerHTML=`<div class="status ${kind}">${text}</div>`}
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb='cb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');const q=new URLSearchParams({...params,action,key:C.API_KEY,callback:cb,_:Date.now()});let timer;window[cb]=data=>{clearTimeout(timer);delete window[cb];s.remove();resolve(data)};s.onerror=()=>{clearTimeout(timer);delete window[cb];s.remove();reject(new Error('Falha de comunicação'))};timer=setTimeout(()=>{delete window[cb];s.remove();reject(new Error('Tempo esgotado'))},20000);s.src=C.API_URL+'?'+q;document.body.appendChild(s)})}
async function post(action,payload){const body=new URLSearchParams({action,key:C.API_KEY,payload:JSON.stringify(payload)});await fetch(C.API_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body});return true}
function updateNet(){ $('#net').textContent=navigator.onLine?'● online — scanner continua local':'● offline — registros protegidos no aparelho'}
async function login(){const id=$('#loginId').value.trim(),pin=$('#loginPin').value.trim();let mons=await all('monitors');let u=mons.find(x=>val(x,['ID Monitor','id','ID'])===id&&val(x,['PIN','pin'])===pin&&val(x,['Ativo?','Ativo','ativo']).toUpperCase()!=='NÃO');if(!u&&navigator.onLine){try{const r=await jsonp('login',{id,pin});if(r.ok){u=r.monitor;await put('monitors',{...u,_key:val(u,['ID Monitor','id','ID'])||id})}}catch(e){}}if(!u){msg($('#loginMsg'),'ID/PIN não encontrado. Faça uma atualização online se este for o primeiro acesso.','bad');return}state.user=u;localStorage.setItem('last_user',id);$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#who').textContent=val(u,['Nome','nome'])+' · '+val(u,['Perfil','perfil']);$('#device').textContent='Dispositivo: '+state.deviceId;await loadActivities();await refreshStats();}
async function loadActivities(){const p=await all('program'),sel=$('#activity');sel.innerHTML='';if(!p.length){sel.innerHTML='<option value="GERAL">GERAL / CREDENCIAMENTO</option>';return}p.forEach((x,i)=>{const code=val(x,['Código Atividade','Código','ID','codigo'])||String(i+1);const name=val(x,['Atividade','Título','Nome','atividade'])||code;const block=val(x,['Bloco','Turno','bloco']);const o=document.createElement('option');o.value=code;o.dataset.name=name;o.dataset.block=block;o.textContent=(block?block+' — ':'')+name;sel.appendChild(o)})}
async function startScanner(){if(!$('#door').value.trim()){alert('Informe a porta/local.');return}$('#scanCard').classList.remove('hidden');$('#start').disabled=true;state.running=true;const mov=$('#movement').value;$('#mode').textContent=mov;$('#mode').className='bigmode '+(mov==='ENTRADA'?'entrada':'saida');try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('#video').srcObject=state.stream;await $('#video').play();if('BarcodeDetector'in window){state.detector=new BarcodeDetector({formats:['qr_code']});requestAnimationFrame(scanLoop)}else{msg($('#scanMsg'),'Este navegador não oferece leitura QR nativa. Use Chrome atualizado ou a digitação de emergência.','warn')}}catch(e){msg($('#scanMsg'),'Não foi possível abrir a câmera. Autorize a câmera para este site.','bad')}}
async function scanLoop(ts){if(!state.running)return;if(state.detector&&ts-state.lastDetect>350){state.lastDetect=ts;try{const codes=await state.detector.detect($('#video'));if(codes.length)await processScan(codes[0].rawValue)}catch(e){}}requestAnimationFrame(scanLoop)}
function stopScanner(){state.running=false;if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null;$('#scanCard').classList.add('hidden');$('#start').disabled=false}
async function processScan(raw){const n=extractQR(raw);if(!n){msg($('#scanMsg'),'QR não reconhecido: não encontrei os 8 dígitos da inscrição.','bad');return}const base=await all('base'),person=base.find(x=>val(x,['Nº Inscrição','Número Inscrição','Inscrição','N° Inscrição'])===n);if(!person){msg($('#scanMsg'),`Inscrição ${n} não está na BASE local.`,'bad');return}const recs=await all('records'),mov=$('#movement').value,act=$('#activity').value,now=new Date();const last=recs.filter(r=>r.registration===n&&r.activityCode===act&&r.movement===mov).sort((a,b)=>b.timestamp.localeCompare(a.timestamp))[0];const diff=last?(now-new Date(last.timestamp))/1000:99999;const duplicate=diff<=Number(C.DUPLICATE_SECONDS||10);const opt=$('#activity').selectedOptions[0];const rec={id:uid(),timestamp:now.toISOString(),qr:String(raw),registration:n,activityCode:act,activity:opt?.dataset.name||opt?.textContent||act,block:opt?.dataset.block||'',movement:mov,door:$('#door').value.trim(),deviceId:state.deviceId,monitorId:val(state.user,['ID Monitor','id','ID']),monitorName:val(state.user,['Nome','nome']),participantName:val(person,['Nome','Nome Participante','Participante']),email:val(person,['E-mail','Email','e-mail']),classification:duplicate?'DUPLICADO_LOCAL':'PENDENTE_APURAÇÃO',valid:!duplicate,syncStatus:'PENDENTE'};await put('records',rec);if(duplicate)msg($('#scanMsg'),`${rec.participantName||n} — possível duplicidade (${Math.round(diff)} s). Registro preservado para auditoria.`,'warn');else msg($('#scanMsg'),`${mov}: ${rec.participantName||n} — ${n}`,(mov==='ENTRADA'?'ok':'info'));await refreshStats();await renderRecords();await new Promise(r=>setTimeout(r,900))}
async function downloadData(){if(state.running){msg($('#syncMsg'),'Encerre o scanner antes de sincronizar.','warn');return}if(!navigator.onLine){msg($('#syncMsg'),'Sem internet. Os dados locais continuam disponíveis.','warn');return}msg($('#syncMsg'),'Baixando dados da planilha…','info');try{const r=await jsonp('bootstrap',{device:state.deviceId});if(!r.ok)throw new Error(r.error||'Servidor recusou');await replace('monitors',r.monitors||[]);await replace('base',r.base||[]);await replace('program',r.program||[]);await replace('config',r.config||[]);await loadActivities();await refreshStats();msg($('#syncMsg'),`Atualização concluída: ${(r.base||[]).length} participantes e ${(r.program||[]).length} itens de programação.`,'ok')}catch(e){msg($('#syncMsg'),'Falha ao atualizar: '+e.message,'bad')}}
async function uploadRecords(){if(state.running){msg($('#syncMsg'),'Encerre o scanner antes de sincronizar.','warn');return}const recs=(await all('records')).filter(r=>r.syncStatus!=='CONFIRMADO');if(!recs.length){msg($('#syncMsg'),'Não há registros pendentes.','ok');return}if(!navigator.onLine){msg($('#syncMsg'),'Sem internet. Nada foi apagado.','warn');return}msg($('#syncMsg'),`Enviando ${recs.length} registros…`,'info');try{await post('sync',recs);await new Promise(r=>setTimeout(r,1800));const ids=recs.map(r=>r.id);const chk=await jsonp('confirm',{ids:ids.join(',')});const confirmed=new Set(chk.confirmed||[]);for(const r of recs)if(confirmed.has(r.id))await put('records',{...r,syncStatus:'CONFIRMADO'});await refreshStats();msg($('#syncMsg'),`${confirmed.size} de ${recs.length} registros confirmados na planilha. Os demais permanecem no aparelho.` ,confirmed.size===recs.length?'ok':'warn')}catch(e){msg($('#syncMsg'),'Falha na sincronização: '+e.message+'. Os registros continuam no aparelho.','bad')}}
async function refreshStats(){const r=await all('records'),b=await all('base');$('#pending').textContent=r.filter(x=>x.syncStatus!=='CONFIRMADO').length;$('#total').textContent=r.length;$('#baseCount').textContent=b.length}
async function renderRecords(){const r=(await all('records')).sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,80);$('#records').innerHTML=r.map(x=>`<div class="item"><b>${x.movement}</b> · ${x.participantName||x.registration}<br><span class="muted">${new Date(x.timestamp).toLocaleString('pt-BR')} · ${x.door} · ${x.activity} · ${x.syncStatus}${x.classification==='DUPLICADO_LOCAL'?' · DUPLICADO':''}</span></div>`).join('')||'<p class="muted">Nenhum registro.</p>'}
async function backup(){const data={exportedAt:new Date().toISOString(),device:state.deviceId,records:await all('records')};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`III_FPBF_BACKUP_${state.deviceId}_${new Date().toISOString().replace(/[:.]/g,'-')}.json`;a.click();URL.revokeObjectURL(a.href)}
$$('[data-view]').forEach(b=>b.onclick=async()=>{$$('.view').forEach(v=>v.classList.add('hidden'));$('#view-'+b.dataset.view).classList.remove('hidden');if(b.dataset.view==='records')await renderRecords();if(b.dataset.view==='sync')await refreshStats()});
$('#btnLogin').onclick=login;$('#logout').onclick=()=>location.reload();$('#start').onclick=startScanner;$('#stop').onclick=stopScanner;$('#manualBtn').onclick=()=>{const x=$('#manual').value.trim();if(x){processScan(x);$('#manual').value=''}};$('#download').onclick=downloadData;$('#upload').onclick=uploadRecords;$('#backup').onclick=backup;window.addEventListener('online',updateNet);window.addEventListener('offline',updateNet);window.addEventListener('beforeunload',stopScanner);state.deviceId=deviceId();updateNet();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
